services:
  mariadb:
    container_name: mariadb
    volumes:
      - /home/cestevez/data/db_data:/var/lib/mysql
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    #environment:
      #- DB_NAME=${DB_NAME}
      #- DB_USER=${DB_USER}
      #- DB_PASSWORD=${DB_PASSWORD}
      #- DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - netception

  wordpress:
    container_name: wordpress
    volumes:
      - /home/cestevez/data/wp_data:/var/www/html
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    #environment:
      #- DB_HOST=mariadb:3306
      #- DB_NAME=${DB_NAME}
      #- DB_USER=${DB_USER}
      #- DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - netception
    depends_on:
      - mariadb
    
networks:
  netception:
    driver: bridge



