services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      - data_base:/var/lib/mysql
    networks:
      - netception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      DB_HOST: mariadb:3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      URL: https://localhost #substitute localhost by ${DOMAIN_NAME} when editing hosts! 
      TITLE: ${TITLE}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      USER_NAME: ${USER_NAME}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - netception
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress_files:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - netception

volumes:
  data_base:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      #device: '/Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db'
      device: '/home/cestevez/data/wordpress_db'
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      #device: '/Users/carinaestevezorth/Documents/42curriculum/data/wordpress_data'
      device: '/home/cestevez/data/wordpress_files'

# volumes:
#   data_base:
#   wordpress_data:

networks:
  netception:
    driver: bridge

# secrets:
#   db_root_password:
#     file: ./db_root_password
