services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_WP_DATABASE: ${MYSQL_WP_DATABASE}
      MYSQL_WP_USER: ${MYSQL_WP_USER}
      MYSQL_WP_PASSWORD: ${MYSQL_WP_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      - /home/cestevez/data/wordpress_db:/var/lib/mysql
      #- /Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db:/var/lib/mysql
    networks:
      - netception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_WP_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_WP_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_WP_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      - /home/cestevez/data/wordpress_files:/var/www/html
      #- /Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db:/var/www/html
    networks:
      - netception
# volumes:
#   /home/cestevez/data/wordpress_db:
#   external: true
  #/Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db:

networks:
  netception:
    driver: bridge
# secrets:
#   db_root_password:
#     file: ./db_root_password