services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      - data_base:/var/lib/mysql
    networks:
      - netception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      # WORDPRESS_URL: http://localhost:8080
      # ADMIN_USER: admin
      # ADMIN_PASSWORD: admin_password
      # ADMIN_EMAIL: admin@example.com
      # USER_NAME: user
      # USER_EMAIL: user@example.com
      # USER_PASSWORD: user_password
      # secrets:
      #   - db_root_password
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - netception
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress_files:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - netception

volumes:
  data_base:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      #device: '/Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db'
      device: '/home/cestevez/data/wordpress_db'
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      #device: '/Users/carinaestevezorth/Documents/42curriculum/data/wordpress_data'
      device: '/home/cestevez/data/wordpress_files'

# volumes:
#   data_base:
#   wordpress_data:

networks:
  netception:
    driver: bridge

# secrets:
#   db_root_password:
#     file: ./db_root_password
