services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data_base:/var/lib/mysql
    networks:
      - netception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      DB_HOST: mariadb:3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      URL: https://${DOMAIN_NAME}
      TITLE: ${TITLE}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      USER_NAME: ${USER_NAME}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - netception

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress_files:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - netception

volumes:
  data_base:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cestevez/data/wordpress_db'
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cestevez/data/wordpress_files'

networks:
  netception:
    driver: bridge