services:
  mariadb:
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      #- /home/cestevez/data/wordpress_db:/var/lib/mysql
      - /Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db:/var/lib/mysql
    networks:
      - netception

volumes:
  #/home/cestevez/data/wordpress_db:
  /Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db:

networks:
  netception:
    driver: bridge
	
# secrets:
#   db_root_password:
#     file: ./db_root_password