services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      - data_base:/var/lib/mysql
      #- /home/cestevez/data/wordpress_db:/var/lib/mysql
      #- /Users/carinaestevezorth/Documents/42curriculum/data/wordpress_db:/var/lib/mysql
    networks:
      - netception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      # secrets:
      #   - db_root_password
    volumes:
      - wordpress_data:/var/www/html
      # - /home/cestevez/data/wordpress_files:/var/www/html
      # - /Users/carinaestevezorth/Documents/42curriculum/data/wordpress_data:/var/www/html
    networks:
      - netception

volumes:
  data_base:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cestevez/data/wordpress_db'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cestevez/data/wordpress_files'

networks:
  netception:
    driver: bridge

# secrets:
#   db_root_password:
#     file: ./db_root_password
